server:
  port: 8004

spring:
  application:
    name: orders
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 5

feign:
  hystrix:
    enabled: true
