server:
  port: 8003
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 5

zuul:
  routes:
    user-ervices:
      path: /api/user/**
      serviceId: users
    order-ervices:
      path: /api/order/**
      serviceId: orders
